nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-sources.cjs

enableStrictSsl: false

#httpProxy: "http://localhost:3128"
#httpsProxy: "http://localhost:3128"

#npmRegistryServer: "http://nexus.mtsit.local:8081/repository/npm-group/"
##npmRegistryServer: "https://registry.yarnpkg.com"
#
#npmScopes:
#  mts-ds:
#    npmRegistryServer: "https://nexus.design.mts.ru/repository/components/"
#  sol:
#    npmRegistryServer: "http://nexus.mtsit.local:8081/repository/npm-group/"
#
#unsafeHttpWhitelist:
#  - "nexus.mtsit.local"
