nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-sources.cjs

enableStrictSsl: false

#httpProxy: "http://localhost:3128"
#httpsProxy: "http://localhost:3128"

#npmRegistryServer: "https://registry.yarnpkg.com"WW
